@startuml SaleSystem

skinparam classAttributeIconSize 0

class Product {
    - ID: std::string
    - name: std::string
    - price: float
    - inStock: float
    + setPrice(p: float)
    + getPrice(): float
}

class PaymentMethod {
    + {abstract} ~PaymentMethod()
    + {abstract} doPayment()
}

class Order {
    - ID: std::string
    - name: std::string
    - phoneNumber: std::string
    - address: std::string
    - list: std::vector<Product>
    - p: PaymentMethod*
    + input(l: std::vector<Product>)
    + setPaymentMethod(pm: PaymentMethod*)
    + totalPrice(): float
    + showPaymentMethod()
}

class ATM {
    + doPayment()
}

class ZaloPay {
    + doPayment()
}

class MoMo {
    + doPayment()
}

Order o-- Product
Order o-up-> PaymentMethod
PaymentMethod <|-- ATM
PaymentMethod <|-- ZaloPay
PaymentMethod <|-- MoMo

@enduml
