Content-Type: multipart/mixed; boundary="------------CGZ0deQklpGNx23mQtJQdL5q"
Message-ID: <b15fe3d5-0b63-41f5-b08f-fe05059e0709@example.com>
Date: Sun, 26 Nov 2023 20:11:40 +0700
MIME-Version: 1.0
User-Agent: Mozilla Thunderbird
Content-Language: en-US
To: abc@example.com
From: abc <abc@example.com>
Subject: td

This is a multi-part message in MIME format.
--------------CGZ0deQklpGNx23mQtJQdL5q
Content-Type: text/plain; charset=UTF-8; format=flowed
Content-Transfer-Encoding: 7bit

td

--------------CGZ0deQklpGNx23mQtJQdL5q
Content-Type: text/plain; charset=UTF-8; name="References.txt"
Content-Disposition: attachment; filename="References.txt"
Content-Transfer-Encoding: base64

aHR0cHM6Ly93d3cuZ29saW51eGNsb3VkLmNvbS9jaGVjay10aHJlYWRzLXBlci1wcm9jZXNz
LWNvdW50LXByb2Nlc3Nlcy8KaHR0cHM6Ly9tZWRpdW0uY29tL3N3bGgvbGV0cy13cml0ZS1h
LWNoYXQtYXBwLWluLXB5dGhvbi1mNjc4M2E5YWMxNzAKaHR0cHM6Ly9ncGNvZGVyLmNvbS8z
Njc5LXhheS1kdW5nLXVuZy1kdW5nLWNsaWVudC1zZXJ2ZXItdm9pLXNvY2tldC10cm9uZy1q
YXZhLwoKCgpodHRwczovL2Fza3VidW50dS5jb20vcXVlc3Rpb25zLzgxNTg3NC9pbXBvcnRl
cnJvci1uby1uYW1lZC10a2ludGVyLXBsZWFzZS1pbnN0YWxsLXRoZS1weXRob24zLXRrLXBh
Y2thZ2UKc3VkbyBhcHQtZ2V0IGluc3RhbGwgcHl0aG9uMy10ayBJbnN0YWxscyB0a2ludGVy
IGZvciBQeXRob24zLngueAoKCiMgMApodHRwczovL3JlYWxweXRob24uY29tL3B5dGhvbi1z
b2NrZXRzLwojIDEKCiMgMgoKCiJrZXkiIDogdmFsdWUKCnsiYSI6IDEsICJiIjogMn0K

--------------CGZ0deQklpGNx23mQtJQdL5q--
