USE [master]
GO
IF DB_ID('QLTHAMQUAN') IS NOT NULL
	DROP DATABASE QLTHAMQUAN
GO
CREATE DATABASE QLTHAMQUAN
GO
USE QLTHAMQUAN
GO

CREATE TABLE TINH_THANH (
	QUOCGIA NCHAR(5),
	MATINHTHANH NCHAR(5),
	TENTT NVARCHAR(30),
	DANSO INT,
	DIENTICH FLOAT

	CONSTRAINT PK_TT
	PRIMARY KEY(MATINHTHANH),
	CONSTRAINT UQ_TT
	UNIQUE(QUOCGIA, MATINHTHANH)
)

CREATE TABLE QUOC_GIA (
	MAQG NCHAR(5),
	TENQG NVARCHAR(20),
	THUDO NCHAR(5),
	DANSO INT,
	DIENTICH FLOAT

	CONSTRAINT PK_QG
	PRIMARY KEY(MAQG)
)

CREATE TABLE DIEM_THAM_QUAN (
	MADTQ NCHAR(10),
	TENDTQ NVARCHAR(30),
	TINHTHANH NCHAR(5),
	QUOCGIA NCHAR(5),
	DACDIEM NVARCHAR(50)

	CONSTRAINT PK_DTQ
	PRIMARY KEY(MADTQ)
)

ALTER TABLE TINH_THANH
ADD
	CONSTRAINT FK_TT_QG
	FOREIGN KEY(QUOCGIA)
	REFERENCES QUOC_GIA(MAQG)

ALTER TABLE QUOC_GIA
ADD 
	CONSTRAINT FK_QG_TT
	FOREIGN KEY(MAQG, THUDO)
	REFERENCES TINH_THANH(QUOCGIA, MATINHTHANH)

ALTER TABLE DIEM_THAM_QUAN
ADD
	CONSTRAINT FK_DTQ_TT
	FOREIGN KEY(QUOCGIA, TINHTHANH)
	REFERENCES TINH_THANH(QUOCGIA, MATINHTHANH)


INSERT TINH_THANH
VALUES
(NULL, 'TT001', N'Hà Nội', 2500000, 927.39),
(NULL, 'TT002', N'Huế', 5344000, 5009),
(NULL, 'TT003', N'Tokyo', 12084000, 2187)

INSERT QUOC_GIA
VALUES
('QG001', N'Việt Nam', NULL, 115000000, 331688),
('QG002', N'Nhật Bản', NULL, 129500000, 337834)

UPDATE TINH_THANH
SET QUOCGIA = 'QG001'
WHERE MATINHTHANH = 'TT001'

UPDATE TINH_THANH
SET QUOCGIA = 'QG001'
WHERE MATINHTHANH = 'TT002'

UPDATE TINH_THANH
SET QUOCGIA = 'QG002'
WHERE MATINHTHANH = 'TT003'

UPDATE QUOC_GIA
SET THUDO = 'TT001'
WHERE MAQG = 'QG001'

UPDATE QUOC_GIA
SET THUDO = 'TT003'
WHERE MAQG = 'QG002'

INSERT DIEM_THAM_QUAN
VALUES
('DTQ001', N'Văn Miếu', 'TT001', 'QG001', N'Di tích cổ'),
('DTQ002', N'Hoàng lăng', 'TT002', 'QG001', N'Di tích cổ'),
('DTQ003', N'Tháp Tokyo', 'TT003', 'QG002', N'Di tích cổ')


SELECT DTQ.MADTQ, DTQ.TENDTQ
FROM TINH_THANH TT, QUOC_GIA QG, DIEM_THAM_QUAN DTQ
WHERE TT.QUOCGIA = QG.MAQG
	AND TT.DIENTICH >= 0.01 * QG.DIENTICH
	AND DTQ.TINHTHANH = TT.MATINHTHANH

SELECT QG.MAQG, QG.TENQG, COUNT(TT.MATINHTHANH)
FROM TINH_THANH TT, QUOC_GIA QG
WHERE QG.MAQG = TT.QUOCGIA
GROUP BY QG.MAQG, QG.TENQG
HAVING COUNT(TT.MATINHTHANH) > 30
