USE [master]
GO
IF DB_ID('QLHOINGHI') IS NOT NULL
	DROP DATABASE QLHOINGHI
GO
CREATE DATABASE QLHOINGHI
GO
USE QLHOINGHI
GO

CREATE TABLE BAIBAO (
	STT INT,
	HOINGHI NCHAR(5),
	NAMTOCHUC INT,
	LOAIBAIBAO NVARCHAR(50),
	CHUDE NVARCHAR(50)

	CONSTRAINT PK_BB
	PRIMARY KEY(STT, HOINGHI, NAMTOCHUC),

	CONSTRAINT CK_BB
	CHECK(LOAIBAIBAO IN (N'Toàn văn', N'Tóm tắt'))
)

CREATE TABLE HOINGHI (
	MAHOINGHI NCHAR(5),
	QUOCGIA NVARCHAR(50),
	TENHOINGHI NVARCHAR(50) CONSTRAINT UQ_HN UNIQUE(TENHOINGHI) NOT NULL,
	NAMTHANHLAP INT CONSTRAINT DF_HN DEFAULT(YEAR(GETDATE())),
	NHAXUATBAN NVARCHAR(50)

	CONSTRAINT PK_HN
	PRIMARY KEY(MAHOINGHI),
)

CREATE TABLE TOCHUC (
	HOINGHI NCHAR(5),
	NAMTOCHUC INT,
	DIADIEM NVARCHAR(50),
	BAIBAOTIEUBIEU INT

	CONSTRAINT PK_TC
	PRIMARY KEY(HOINGHI, NAMTOCHUC)
)

ALTER TABLE TOCHUC
ADD
	CONSTRAINT FK_TC_BB
	FOREIGN KEY(BAIBAOTIEUBIEU, HOINGHI, NAMTOCHUC)
	REFERENCES BAIBAO(STT, HOINGHI, NAMTOCHUC),

	CONSTRAINT FK_TC_HN
	FOREIGN KEY(HOINGHI)
	REFERENCES HOINGHI(MAHOINGHI)

ALTER TABLE BAIBAO
ADD
	CONSTRAINT FK_BB_TC
	FOREIGN KEY(HOINGHI, NAMTOCHUC)
	REFERENCES TOCHUC(HOINGHI, NAMTOCHUC)


INSERT HOINGHI
VALUES
('CITA', N'Việt Nam', N'Công nghệ thông tin và ứng dụng', 2023, N'Giáo dục'),
('KES', N'Hoa Kỳ', N'Tri thức và dữ liệu', 2022, N'IEEE')

INSERT TOCHUC
VALUES
('CITA', 2023, N'Đà Nẵng, Việt Nam', NULL),
('KES', 2022, N'Tokyo, Nhật Bản', NULL), 
('KES', 2023, N'Paris, Pháp', NULL)

INSERT BAIBAO
VALUES
(1, 'CITA', 2023, N'Toàn văn', N'Ứng dụng'),
(2, 'CITA', 2023, N'Tóm tắt', N'Nghiên cứu'),
(1, 'KES', 2022, N'Tóm tắt', N'Nghiên cứu'),
(1, 'KES', 2023, N'Toàn văn', N'Ứng dụng'),
(2, 'KES', 2023, N'Toàn văn', N'Ứng dụng')

UPDATE TOCHUC
SET BAIBAOTIEUBIEU = 2
WHERE HOINGHI = 'CITA' AND NAMTOCHUC = 2023

UPDATE TOCHUC
SET BAIBAOTIEUBIEU = 1
WHERE HOINGHI = 'KES' AND NAMTOCHUC = 2022

UPDATE TOCHUC
SET BAIBAOTIEUBIEU = 2
WHERE HOINGHI = 'KES' AND NAMTOCHUC = 2023


SELECT TC.DIADIEM
FROM TOCHUC TC, HOINGHI HN
WHERE TC.HOINGHI = HN.MAHOINGHI AND HN.TENHOINGHI = N'Tri thức và dữ liệu'

SELECT HN.TENHOINGHI, HN.QUOCGIA
FROM TOCHUC TC, HOINGHI HN, BAIBAO BB
WHERE TC.DIADIEM LIKE N'%Nhật%' 
	AND TC.BAIBAOTIEUBIEU = BB.STT 
	AND BB.CHUDE = N'Nghiên cứu'
	AND NOT (BB.LOAIBAIBAO = N'Toàn văn' AND BB.CHUDE = N'Ứng dụng')
	AND TC.HOINGHI = HN.MAHOINGHI

SELECT HN.MAHOINGHI, HN.TENHOINGHI, COUNT(DISTINCT TC.NAMTOCHUC) AS N'SO LAN TO CHUC' , COUNT(BB.STT) AS N'SO BAI BAO'
FROM HOINGHI HN, TOCHUC TC, BAIBAO BB
WHERE HN.MAHOINGHI = TC.HOINGHI AND TC.HOINGHI = BB.HOINGHI AND TC.NAMTOCHUC = BB.NAMTOCHUC
GROUP BY HN.MAHOINGHI, HN.TENHOINGHI