use [master]
go
use QLDETAI
go

-- 35
SELECT MAX(GV.LUONG) AS MAX_LUONG
FROM GIAOVIEN GV

-- 36
SELECT GV.MAGV, GV.HOTEN, GV.LUONG
FROM GIAOVIEN GV
WHERE GV.LUONG = (SELECT MAX(GV.LUONG) AS MAX_LUONG
					FROM GIAOVIEN GV)

-- 37
SELECT MAX(GV.LUONG) AS MAX_LUONG
FROM GIAOVIEN GV
WHERE GV.MABM = 'HTTT'

-- 38
SELECT GV.HOTEN
FROM GIAOVIEN GV
	JOIN BOMON BM ON BM.MABM = GV.MABM
WHERE BM.TENBM =  N'Hệ Thống Thông Tin'
	AND DATEDIFF(DAY, GV.NGSINH, GETDATE()) >= ALL(SELECT DATEDIFF(DAY, GV.NGSINH, GETDATE())
												FROM GIAOVIEN GV
												JOIN BOMON BM ON BM.MABM = GV.MABM
												WHERE BM.TENBM =  N'Hệ Thống Thông Tin')

-- 39
SELECT GV.HOTEN
FROM GIAOVIEN GV
	JOIN BOMON BM ON BM.MABM = GV.MABM
	JOIN KHOA K ON K.MAKHOA = BM.MAKHOA
WHERE K.TENKHOA = N'Công Nghệ Thông Tin'
	AND DATEDIFF(DAY, GV.NGSINH, GETDATE()) <= ALL(SELECT DATEDIFF(DAY, GV.NGSINH, GETDATE())
												FROM GIAOVIEN GV
												JOIN BOMON BM ON BM.MABM = GV.MABM
												JOIN KHOA K ON K.MAKHOA = BM.MAKHOA
												WHERE K.TENKHOA = N'Công Nghệ Thông Tin')

-- 40
SELECT GV.MAGV, GV.HOTEN, GV.LUONG, (SELECT K.TENKHOA
										FROM KHOA K
											JOIN BOMON BM ON BM.MAKHOA = K.MAKHOA
										WHERE GV.MABM = BM.MABM) AS TENKHOA
FROM GIAOVIEN GV
WHERE GV.LUONG = (SELECT MAX(GV.LUONG) AS MAX_LUONG
					FROM GIAOVIEN GV)

-- 41
SELECT GV.MAGV, GV.HOTEN, GV.LUONG
FROM GIAOVIEN GV
WHERE GV.LUONG = (SELECT MAX(GV1.LUONG) AS MAX_LUONG
					FROM GIAOVIEN GV1
					WHERE GV.MABM = GV1.MABM)

-- 42
SELECT DT.TENDT
FROM DETAI DT
EXCEPT
SELECT DT.TENDT
FROM DETAI DT
	JOIN THAMGIADT TG ON TG.MADT = DT.MADT
	JOIN GIAOVIEN GV ON GV.MAGV = TG.MAGV
WHERE GV.HOTEN = N'Nguyễn Hoài An'

-- 43
SELECT DT.TENDT, GV.HOTEN AS GVCNDT
FROM DETAI DT
	JOIN GIAOVIEN GV ON DT.GVCNDT = GV.MAGV
EXCEPT
SELECT DT.TENDT, (SELECT GV.HOTEN
					FROM GIAOVIEN GV
					WHERE GV.MAGV = DT.GVCNDT)
FROM DETAI DT
	JOIN THAMGIADT TG ON TG.MADT = DT.MADT 
	JOIN GIAOVIEN GV ON GV.MAGV = TG.MAGV 
WHERE GV.HOTEN = N'Nguyễn Hoài An'

-- 44
SELECT GV.MAGV, GV.HOTEN
FROM GIAOVIEN GV 
	JOIN BOMON BM ON BM.MABM = GV.MABM
	JOIN KHOA K ON K.MAKHOA = BM.MAKHOA
WHERE K.TENKHOA = N'Công Nghệ Thông Tin'
EXCEPT
SELECT GV.MAGV, GV.HOTEN
FROM GIAOVIEN GV 
	JOIN THAMGIADT TG ON TG.MAGV = GV.MAGV

-- 45
SELECT GV.MAGV, GV.HOTEN
FROM GIAOVIEN GV 
EXCEPT
SELECT GV.MAGV, GV.HOTEN
FROM GIAOVIEN GV 
	JOIN THAMGIADT TG ON TG.MAGV = GV.MAGV

-- 46
SELECT GV.MAGV, GV.HOTEN, GV.LUONG
FROM GIAOVIEN GV
WHERE GV.LUONG > (SELECT GV.LUONG
					FROM GIAOVIEN GV
					WHERE GV.HOTEN = N'Nguyễn Hoài An')

-- 47
SELECT *
FROM GIAOVIEN GV
	JOIN BOMON BM ON BM.TRUONGBM = GV.MAGV
WHERE GV.MAGV IN (SELECT TG.MAGV
					FROM THAMGIADT TG)

-- 48
select gv.*
from GIAOVIEN gv join (select magv,hoten,phai, mabm
						from GIAOVIEN ) gv1
on gv1.HOTEN = gv.HOTEN and gv1.MABM = gv.MABM and
gv1.PHAI = gv.phai and gv1.MAGV <> gv.magv

-- 49
SELECT GV.HOTEN
FROM GIAOVIEN GV
WHERE GV.LUONG >= ANY(SELECT GV.LUONG
						FROM GIAOVIEN GV
							JOIN BOMON BM ON BM.MABM = GV.MABM
						WHERE BM.TENBM = N'Công nghệ phần mềm')

-- 50
SELECT GV.HOTEN, GV.LUONG
FROM GIAOVIEN GV
WHERE GV.LUONG >= ALL(SELECT GV.LUONG
						FROM GIAOVIEN GV
							JOIN BOMON BM ON BM.MABM = GV.MABM
						WHERE BM.TENBM = N'Hệ thống thông tin')

-- 51
SELECT TENKHOA
FROM GIAOVIEN GV
	JOIN BOMON BM ON BM.MABM = GV.MABM
	JOIN KHOA K ON K.MAKHOA = BM.MAKHOA
GROUP BY K.MAKHOA, K.TENKHOA
HAVING COUNT(*) >= ALL(SELECT COUNT(*)
						FROM GIAOVIEN GV
							JOIN BOMON BM ON BM.MABM = GV.MABM
							JOIN KHOA K ON K.MAKHOA = BM.MAKHOA
						GROUP BY K.MAKHOA, K.TENKHOA)

-- 52
SELECT GV.HOTEN, COUNT(*)
FROM GIAOVIEN GV
	JOIN DETAI DT ON DT.GVCNDT = GV.MAGV	
GROUP BY GV.MAGV, GV.HOTEN
HAVING COUNT(*) >= ALL(SELECT COUNT(*)
						FROM GIAOVIEN GV
							JOIN DETAI DT ON DT.GVCNDT = GV.MAGV
						GROUP BY GV.MAGV)

-- 53
SELECT MABM
FROM GIAOVIEN
GROUP BY MABM
HAVING COUNT(*) >= ALL( SELECT COUNT(*)
						FROM GIAOVIEN
						GROUP BY MABM)

-- 54
SELECT GV.MAGV, BM.MABM
FROM GIAOVIEN GV
	JOIN BOMON BM ON BM.MABM = GV.MABM
	JOIN THAMGIADT TG ON TG.MAGV = GV.MAGV
GROUP BY GV.MAGV, BM.MABM
HAVING COUNT(*) >= ALL(SELECT COUNT(*)
					FROM GIAOVIEN GV
						JOIN BOMON BM ON BM.MABM = GV.MABM
						JOIN THAMGIADT TG ON TG.MAGV = GV.MAGV
					GROUP BY GV.MAGV)

-- 55
SELECT GV.MAGV, COUNT(*)
FROM THAMGIADT TG
	JOIN GIAOVIEN GV ON GV.MAGV = TG.MAGV
WHERE GV.MABM = N'HTTT'
GROUP BY GV.MAGV
HAVING COUNT(*) >= ALL(SELECT COUNT(*)
						FROM THAMGIADT TG
							JOIN GIAOVIEN GV ON GV.MAGV = TG.MAGV
						WHERE GV.MABM = N'HTTT'
						GROUP BY GV.MAGV)

-- 56
SELECT GV.HOTEN, BM.TENBM, COUNT(*)
FROM GIAOVIEN GV
	JOIN NGUOITHAN NT ON NT.MAGV = GV.MAGV
	JOIN BOMON BM ON BM.MABM = GV.MABM
GROUP BY GV.HOTEN, BM.TENBM
HAVING COUNT(*) >= ALL(SELECT COUNT(*)
					FROM GIAOVIEN GV
						JOIN NGUOITHAN NT ON NT.MAGV = GV.MAGV
						JOIN BOMON BM ON BM.MABM = GV.MABM
					GROUP BY GV.HOTEN, BM.TENBM)

-- 57
SELECT GV.HOTEN, COUNT(*)
FROM GIAOVIEN GV
	JOIN DETAI DT ON DT.GVCNDT = GV.MAGV
	JOIN BOMON BM ON BM.TRUONGBM = GV.MAGV
GROUP BY GV.HOTEN
HAVING COUNT(*) >= ALL(SELECT COUNT(*)
						FROM GIAOVIEN GV
							JOIN DETAI DT ON DT.GVCNDT = GV.MAGV
							JOIN BOMON BM ON BM.TRUONGBM = GV.MAGV
						GROUP BY GV.HOTEN)